      - name: üîç Find Web Root
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -c "set ftp:ssl-allow no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; find . -name index.html"

      - name: üöÄ Deploy via FTP
        run: |
          lftp -c "set ftp:ssl-allow no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; mirror -R --verbose ./build/web/ /public_html/"
pen -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; mirror -R --verbose ./build/web/ /public_html/"
